framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: true

when@dev:
    framework:
        router:
            strict_requirements: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
