type: object
properties:
    data:
        type: array
        items: { $ref: '#/components/schemas/Permission' }
    meta:
        type: object
        properties:
            pagination: { $ref: '#/components/schemas/Pagination' }
